musicas = [
  'Dance me to the end of love - Leonardo Cohen',
  'Hey there Delilah - Plain White T\'s',
  'Love me \'till the end - The Pogues',
  'Pra você guardei o amor - Nando Reis',
  'Baby can I hold you - Tracy Chapman',
  'Deus, você e eu - Saulo Viana',
  'Ai que saudade d\'ocê - Zeca baleiro',
  'Parece que foi ontem - Bruna Karla',
  'Minha felicidade - Roberta Campos',
  'Céu se santo amaro - Osvaldo Montenegro',
  'Pra sonhar - Marcelo Jeneci',
  'My girl - the temptations',
  'Satellite - eddie Vedder',
  'Unchained melody - the righteous brothers',
  'No recreio - cássia eller',
  'Eu te devoro - Djavan',
  'A seta e o alvo - Paulinho Moska',
  'Pela última vez - Nx zero',
  'Nx zero',
  'Equalize - Pitty',
  'Chiclete com banana',
  'She will be loved - maroon 5',
  'Somewhere only we know - Keane',
  'Corazon partio - Alejandro Sanz',
  'Tanto - skank',
  'Começo, meio e fim - roupa nova',
  'O lugar perfeito pro amor viver - Sandy e junior',
  'Alcione',
  'You\'ll be in my heart - Phill Collins',
  'Vou amar te - Henrique Cerqueira',
  'Te amo - Bruna Karla',
  'Te ver superar - Jota Quest',
  'Something - Beatles',
  'You and I - Stevie Wonder',
  'Sobre o amor - João Alexandre',
  'Pétala - Djavan',
  'Love never felt so good - Michael Jackson',
  'Crime - Pâmela',
  'Here without you - 3 doors down',
  'Aerosmith',
  'Creed',
  'Closer - Chainsmokers',
  'Partilhar - Rubel',
  'Oração - a banda mais bonita da cidade',
  'Um mundo ideal - Aladdin',
  'Tão distante - Tuca Oliveira',
  'Se vc quer saber se tem alguém q goste + de vc',
  'Can\'t take my eyes - Joseph Vincent',
  'Amor perfeito - Fernando e Sorocaba',
  'Todo dia até morrer - Rodolfo abrantes',
  'Não há limites - quatro por um',
  'Meu bem querer - Sérgio saas',
  'Seremos um - Mariana Aguiar',
  'As marcas desse amor - banda universo',
  'Cidadão quem - dia especial',
  'A carta e o soldado - Henrique Cerqueira',
  'Impossível não te amar - Nádia aantolli'
]

adicionadas = [
  'Fulminante - Mumuzinho',
  'Camisa 10 - Turma do pagode',
  'A vida é boa com você - Bryan Behr',
  "You're still the one - Shania Twain",
  'De janeiro a janeiro - Roberta Campos e Nando Reis',
  "Livina on' a prayer - Bon Jovi",
  'Perfect - Ed Sheeran',
  'Só hoje - Jota Quest',
  'Um amor puro - Djavan',
  'Slave to love - Brian Ferry',
  'Forever - Kiss',
  'Borbulhas de amor - Fagner',
  'Mágica - Calcinha Preta',
  'Diga sim pra mim - Desejo de Menina',
  'Meu anjo azul - Forró Anjo Azul',
  'Eu te amo tanto - Meninos de barão',
  'Isso é imortal - gatinha manhosa',
  'Feitos um pro outro - Desejo de menina',
  'Pétalas neon - noda de caju',
  'Carta branca - banda magníficos',
  'Manchete nos jornais - Calcinha Preta',
  'De janeiro a janeiro - Limão com mel',
  'Fica comigo - limão com mel',
  'Pra sempre - limão com mel',
  'Pode se achegar - Agnes e Tiago Iorc',
  'Felicidade - Marcelo Jeneci',
  'Parbólicas - Dingo',
  'Layla - Eric Clapton',
  'New light - John Mayer',
  'Só você - Fábio Jr',
  'How deep is your love - Bee Gees',
  'A dama de vermelho - Waldik Soriano',
  'Sentir teu calor - noda de caju',
  "(Everything I do) I do it for you",
  'Heaven - Bryan Adams',
  'The Outfield - Your love',
  'The time of my life - Bill Medley, Jennifer Warnes',
  'Nós dois - Pedro Valença',
  'Não há nada mais lindo do que amanhecer',
  'A dança - Tiago nacarato',
  'De olhos abertos - Pedro Valença',
  'Caneta e papel - os Arrais',
  'Só nos dois - Tim Bernardes',
  'High school musical',
  'Você me faz tão bem - Hélvio Sodré',
  'Um sonho de amor - Edson e Batista Lima',
  'Evidências - Chitãozinho e Xororó',
  'Paraquedas - Gabriel Diniz',
  'Nocaute - Jorge e Mateus',
  'Os anjos cantam - Jorge e Mateus',
  'Está noite foi maravilhosa - Leonardo',
  'É por você que eu canto - Leandro e Leonardo',
  'É você - Marisa Monte',
  'Meet me halfway - Black eyed peas',
  'Milk and toast and honey - Roxette',
  'Hungry eyes - Eric Carmen',
  'Every breath you take - The Police',
  'Sorriso resplandecente - Dragon Ball',
  'Morando do nordeste - Lairton',
  'Eles se amam - Vocal Livre',
  'ALL star - Nando Reis',
  'Ana Vitória',
  'Por onde andei - Nando Reis',
  'Pensando em você - Moska',
  'Por você - Frejat',
  'Meu abrigo - Melim',
  'Olhos certos - Detonautas',
  'Você me faz tão bem - Detonautas',
  "I won't give up - Jason Mraz",
  'Envelhecer com você - Lorena Chaves',
  'Se for com você - Estevão Queiroga',
  'Velha infância - Tribalistas',
  'Sala de reboco - Luiz Gonzaga',
  'Give me love - Ed Sheeran',
]